<?


###Deutch
$LANG['de']['namelang']="En espa&ntilde;ol: ";
$LANG['de']['search']="B&uacute;squeda en Alem&aacute;n: ";
$LANG['de']['tosearch']="&iexcl;Buscar!";
$LANG['de']['fullscreen']="";
$LANG['de']['goback']="Regresar";
$LANG['de']['word']="Palabra";
$LANG['de']['translation']="Traducci&oacute;n";
$LANG['de']['reference']="Referencias";
$LANG['de']['also']="V&eacute;ase";
$LANG['de']['sonof']="hijo de";
$LANG['de']['addItem']="Agregar Palabra";
$LANG['de']['addUser']="Agregar Usuario";
$LANG['de']['changePass']="Cambiar Password";
$LANG['de']['add']="Agregar";
$LANG['de']['edit']="Editar";
$LANG['de']['del']="Borrar";
$LANG['de']['save']="Guardar";
$LANG['de']['modification']="Modificaci&oacute;n exitosa";
$LANG['de']['error']="Un error sucedi&oacute; al realizar la &uacute;ltima operaci&oacute;n";
$LANG['de']['view']="Ver";
$LANG['de']['de']="Alem&aacute;n";
$LANG['de']['es']="Espa&ntilde;ol";
$LANG['de']['level']="Nivel";
$LANG['de']['derived']="Expresiones derivadas:";
$LANG['de']['derivedfrom']="Derivado de";
$LANG['de']['cursives']="Cursivas";
$LANG['de']['link']="link";
$LANG['de']['nosearch']="No exist&eacute;n m&aacute;s registros<br>o no se ha generado una b&uacute;squeda.";
$LANG['de']['previous']="Anteriores 25";
$LANG['de']['next']="Siguientes 25";
$LANG['de']['download']="Descargar";
$LANG['de']['name']='Nombre';

##### Espa&ntilde;ol
$LANG['es']['namelang']="En alem&aacute;n: ";
$LANG['es']['search']="B&uacute;squeda en Espa&ntilde;ol: ";
$LANG['es']['tosearch']="&iexcl;Buscar!";
$LANG['es']['fullscreen']="";
$LANG['es']['goback']="Regresar";
$LANG['es']['word']="Palabra";
$LANG['es']['translation']="Traducci&oacute;n";
$LANG['es']['reference']="Referencias";
$LANG['es']['also']="V&eacute;ase";
$LANG['es']['sonof']="hijo de";
$LANG['es']['addItem']="Agregar Palabra";
$LANG['es']['addUser']="Agregar Usuario";
$LANG['es']['changePass']="Cambiar Password";
$LANG['es']['add']="Agregar";
$LANG['es']['edit']="Editar";
$LANG['es']['del']="Borrar";
$LANG['es']['save']="Guardar";
$LANG['es']['modification']="Modificaci&oacute;n Exitosa";
$LANG['es']['error']="Un error sucedi&oacute; al realizar la &uacute;ltima operaci&oacute;n";
$LANG['es']['view']="Ver";
$LANG['es']['de']="Alem&aacute;n";
$LANG['es']['es']="Espa&ntilde;ol";
$LANG['es']['level']="Nivel";
$LANG['es']['derived']="Expresiones derivadas:";
$LANG['es']['derivedfrom']="Derivado de";
$LANG['es']['cursives']="Cursivas";
$LANG['es']['link']="link";
$LANG['es']['nosearch']="No exist&eacute;n m&aacute;s registros<br>o no se ha generado una b&uacute;squeda.";
$LANG['es']['previous']="Anteriores 25";
$LANG['es']['next']="Siguientes 25";
$LANG['es']['download']="Descargar";
$LANG['es']['name']='Nombre';
$LANG['es']['surname']="Apellidos";
$LANG['es']['inst']="Instituci&oacute;n";
$LANG['es']['country']="Pa&iacute;s";
$LANG['es']['mail']="E-Mail";
$LANG['es']['accept']="Continuar";
$LANG['es']['pass1']="Contrase&ntilde;a";
$LANG['es']['pass2']="Repetir Contrase&ntilde;a";
$LANG['es']['login']="E-Mail";
$LANG['es']['mandatory']="Campo Obligatorio";
$LANG['es']['warnmail']="La direcci&oacute;n  de e-mail no es v&aacute;lida";
$LANG['es']['warnnama']="Es obligatorio dar un nombre";
$LANG['es']['warnsurnama']="Es obligatorio dar apellidos";
$LANG['es']['warncounty']="Es obligatorio escoger un pa&iacute;s";
$LANG['es']['warnpass']="Es obligatorio escoger una contrase&ntilde;a de acceso";
$LANG['es']['warnpassequal']="Las contrase&ntilde;as de acceso no coinciden";
$LANG['es']['warnlogin']="Usuario o contrase&ntilde;a incorrectos";
$LANG['es']['warnlogin2']="Direcci&oacute;n mail no registrada";
$LANG['es']['warnlogin3']="La contrase&ntilde;a ha sido enviada v&iacute;a e-mail";
$LANG['es']['warnlogin4']="No se puede enviar correo. Favor de comunicarse con Antonio Ziri&oacute;n";
$LANG['es']['errordbreg']="La direcci&oacute;n de e-mail que diste ya est&aacute; registrada";
$LANG['es']['recover']="Recuperar Contrase&ntilde;a";
$LANG['es']['mailrecover']="Diccionario Husserl: Recuperacion Contrase&ntilde;a";
$LANG['es']['mailrecovermsg']="Has solicitado la recuperacion de tu contrasena la cual es: ";
$LANG['es']['welcome']="&iexcl;Bienvenido! ";
$LANG['es']['diccionario']="Diccionario Husserl";
$LANG['es']['wish']="Si quieres registrarte para tener acceso al <i>Diccionario Husserl</i> llena por favor la siguiente forma.";
$LANG['es']['regdisclaimer']="La informaci&oacute;n que solicitamos ser&aacute; usada exclusivamente para control de acceso al Diccionario Husserl";
$LANG['es']['changepass']="Cambio de Contrase&ntilde;a";
$LANG['es']['accountconfig']="Configuraci&oacute;n de Cuenta";
$LANG['es']['currentpass']="Contrase&ntilde;a Actual";
$LANG['es']['passincorrect1']='Contrase&ntilde;a Original Incorrecta';
$LANG['es']['passincorrect2']='La contrase&ntilde;a nueva debe constar de 5 caracteres como m&iacute;nimo';
$LANG['es']['passincorrect3']='Las contrase&ntilde;as no coinciden';
$LANG['es']['passcorrect']='Tu contrase&ntilde;a ha sido modificada';
$LANG['es']['definition']='L&eacute;xico biling&uuml;e (alem&aacute;n y espa&ntilde;ol) de expresiones definidas a partir de las obras de<br> Edmund Husserl (1859-1938)';
$LANG['es']['linkreg']="&iquest;No tienes una cuenta? <a href='".URL."?action=siteregistry'>Haz click aqu&iacute; para obtener una.</a>";
$LANG['es']['linkforget']="Si olvidaste tu contrase&ntilde;a <a href='".URL."?action=siteaccess&recoverpasswd=1'>haz click aqu&iacute; para recuperarla.</a>";
$LANG['es']['registersuccess']='<div style="font-family: berliner,arial,sans-serif,helvetica;color: #521410; text-align: center;">La siguiente cuenta ha quedado registrada con &eacute;xito: </div>';
$LANG['es']['footer1']='<div style="font-family: berliner,arial,sans-serif,helvetica;font-size: 12px;color: #521410; text-align: center;">
El proyecto del Diccionario Husserl es desarrollado por <a href="mailto:azirionq@yahoo.com.mx">Antonio Ziri&oacute;n Quijano</a> 
en el <a target=_top href="http://www.filosoficas.unam.mx">Instituto de Investigaciones Filos&oacute;ficas</a> de la 
<a target=_top href="http://www.unam.mx">Universidad Nacional Aut&oacute;noma de M&eacute;xico.</a></div>';
$LANG['es']['footer2']='<div style="font-family: berliner,arial,sans-serif,helvetica;font-size: 11px;color: #521410; text-align: center;">
(C) Antonio Ziri&oacute;n Quijano, 2006.  Derechos reservados conforme a la ley.</div>';

//$LANG['es']['']="";
//$LANG['es']['']="";

$LANG['en']['name']='Name';
$LANG['en']['surname']="Last Name(s)";
$LANG['en']['inst']="Institution";
$LANG['en']['country']="Country";
$LANG['en']['mail']="E-Mail";
$LANG['en']['accept']="Continue";
$LANG['en']['pass1']="Password";
$LANG['en']['pass2']="Repeat Password";
$LANG['en']['login']="E-Mail";
$LANG['en']['mandatory']="Mandatory Field";
$LANG['en']['warnmail']="E-Mail Address is not valid";
$LANG['en']['warnnama']="It is mandatory to enter a name";
$LANG['en']['warnsurnama']="It is mandatory to enter a last name";
$LANG['en']['warncounty']="It is mandatory to select a country";
$LANG['en']['warnpass']="It is mandatory to select a password";
$LANG['en']['warnpassequal']="Passwords do not match";
$LANG['en']['warnlogin']="Incorrect user or password";
$LANG['en']['warnlogin2']="The given E-mail address has not been registered";
$LANG['en']['warnlogin3']="Password has been sent by e-mail";
$LANG['en']['warnlogin4']="Imposible to send an e-mail. Please contact Antonio Ziri&acute;n";
$LANG['en']['errordbreg']="Address has already been registered";
$LANG['en']['recover']="Retrieve Password";
$LANG['en']['mailrecover']="Husserl Dictionary: Password retrieval";
$LANG['en']['mailrecovermsg']="You have required to retrieve your password, which is:";
$LANG['en']['welcome']="Welcome";
$LANG['en']['diccionario']="Husserl Dictionary";
$LANG['en']['wish']="If you want to register to have access to the Husserl Dictionary, please fill the following form";
$LANG['en']['regdisclaimer']="The requested information will only be used to control the access to the Husserl Dictionary";
$LANG['en']['changepass']="Change your password";
$LANG['en']['accountconfig']="Account configuration";
$LANG['en']['currentpass']="Current Password";
$LANG['en']['passincorrect1']='Original Password is incorrect';
$LANG['en']['passincorrect2']='New password must have at least 5 characters';
$LANG['en']['passincorrect3']='Passwords do not match';
$LANG['en']['passcorrect']='Your password has been changed';
$LANG['en']['definition']='Bilingual (German-Spanish) lexicon of expressions defined on the basis of the works of Edmund Husserl (1859-1938)';
$LANG['en']['linkreg']="Don't have an account? <a href='".URL."?action=siteregistryenglish'>Click here to get one</a>";
$LANG['en']['linkforget']="Forgot your password? <a href='".URL."?action=siteaccessenglish&recoverpasswd=1'>Click here to recover it";
$LANG['en']['registersuccess']='<div style="font-family: berliner,arial,sans-serif,helvetica;color: #521410; text-align: center;>The following account has been successfully registered: ></div>';
$LANG['en']['footer1']='<div style="font-family: berliner,arial,sans-serif,helvetica;font-size: 12px;color: #521410; text-align: center;">
The Husserl Dictionary project is developed by <a href="mailto:azirionq@yahoo.com.mx">Antonio Ziri&oacute;n Quijano</a> at the <a target=_top href="http://www.filosoficas.unam.mx">Instituto de Investigaciones Filos&oacute;ficas of Universidad Nacional Aut&oacute;noma de M&eacute;xico</a></div>';
$LANG['en']['footer2']='<div style="font-family: berliner,arial,sans-serif,helvetica;font-size: 11px;color: #521410; text-align: center;">(C) 2006, Antonio Ziri&oacute;n Quijano</div>';
?>
