<?


###Deutsch
$LANG['de']['namelang']="Auf Spanisch: ";
$LANG['de']['search']="Suche auf Deutsch: ";
$LANG['de']['tosearch']="Suche!";
$LANG['de']['fullscreen']="";
$LANG['de']['goback']="Zur&uuml;ck";
$LANG['de']['word']="Palabra";
$LANG['de']['translation']="Traducci&oacute;n";
$LANG['de']['reference']="Hinweise";
$LANG['de']['also']="Sehen";
$LANG['de']['sonof']="hijo de";
$LANG['de']['addItem']="Agregar Palabra";
$LANG['de']['addUser']="Agregar Usuario";
$LANG['de']['changePass']="Cambiar Password";
$LANG['de']['add']="Agregar";
$LANG['de']['edit']="Editar";
$LANG['de']['del']="Borrar";
$LANG['de']['save']="Guardar";
$LANG['de']['modification']="Modificación Exitosa";
$LANG['de']['error']="Un error sucedi&oacute; al realizar la última operaci&oacute;n";
$LANG['de']['view']="Sehen";
$LANG['de']['de']="Deutsch";
$LANG['de']['es']="Spanisch";
$LANG['de']['level']="Stufe";
$LANG['de']['derived']="Ableitungsausdr&#252;cke:";
$LANG['de']['derivedfrom']="Abgeleitet von";
$LANG['de']['cursives']="Cursivas";
$LANG['de']['link']="link";
$LANG['de']['nosearch']="Es gibt kein Register mehr<br>oder Sie haben keine Suche gestartet";
$LANG['de']['previous']="Die 25 vorhergehende";
$LANG['de']['next']="Die 25 folgende";
$LANG['de']['download']="Herunterladen";
$LANG['de']['name']='Vorname';
$LANG['de']['surname']="Familienname(n)";
$LANG['de']['inst']="Anstalt";
$LANG['de']['country']="Land";
$LANG['de']['mail']="E-Mail";
$LANG['de']['accept']="Fortsetzen";
$LANG['de']['pass1']="Passwort";
$LANG['de']['pass2']="Bitte Passwort wiederholen";
$LANG['de']['login']="E-Mail";
$LANG['de']['mandatory']="Obligatorischer Feld";
$LANG['de']['warnmail']="E-mail Adresse ist nicht gültig";
$LANG['de']['warnnama']="Es ist obligatorisch einen Vorname einzutragen";
$LANG['de']['warnsurnama']="Es ist obligatorisch Familienname(n) einzutragen";
$LANG['de']['warncounty']="Es ist obligatorisch ein Land auszuwählen";
$LANG['de']['warnpass']="Es ist obligatorisch ein Zugangspasswort wählen";
$LANG['de']['warnpassequal']="Die Zugangspassworte stimmen nicht";
$LANG['de']['warnlogin']="Unrichtiger Benutzer oder Passwort";
$LANG['de']['warnlogin2']="E-mail Adresse ist nicht registriert";
$LANG['de']['warnlogin3']="Das Passwort ist durch E-mail abgesendet worden";
$LANG['de']['warnlogin4']="Es ist nicht möglich E-mail zu senden. Bitte verbinden Sie mit Antonio Ziri&oacute;n";
$LANG['de']['errordbreg']="E-mail Adresse ist schon registriert worden";
$LANG['de']['recover']="Passwort wiedererlangen";
$LANG['de']['mailrecover']="Husserl W&ouml;rterbuch: Passwort Wiedererlangung";
$LANG['de']['mailrecovermsg']="Passwort wiedererlangen";
$LANG['de']['welcome']="Wilkommen!";
$LANG['de']['diccionario']="Husserl W&ouml;rterbuch";
$LANG['de']['wish']="Wenn Sie registrieren wollen, um Zugang zu das Husserl W&ouml;rterbuch bekommen, bitte dieses Formular ausf&uuml;llen.";
$LANG['de']['regdisclaimer']="Die geforderte Information wird nur benutzt, um der Zugang zu der Husserl W&ouml;rterbuch zu kontrollieren";
$LANG['de']['changepass']="Passwort wechseln";
$LANG['de']['accountconfig']="Konfiguration des Konto";
$LANG['de']['currentpass']="Aktueller Passwort";
$LANG['de']['passincorrect1']='Origineller Passwort ist unrichtig';
$LANG['de']['passincorrect2']='Das neue Passwort muss mindestens 5 Schriftzeichen enthalten';
$LANG['de']['passincorrect3']='Passworts stimmen nicht';
$LANG['de']['passcorrect']='Ihr Passwort ist gewechselt worden';
$LANG['de']['definition']='Deutsch-spanisches Lexikon husserlscher Ausdr&uuml;cke definiert durch die Werke<br>Edmund Husserls (1859-1938)';
$LANG['de']['linkreg']="Kein Konto? <a href='".URL."?action=siteregistry'>Click hier um ein Konto zu bekommen.</a>";
$LANG['de']['linkforget']="Passwort vergessen? <a href='".URL."?action=siteaccess&recoverpasswd=1'>Click hier um Passwort wiedererlangen.</a>";
$LANG['de']['registersuccess']='<div style="font-family: berliner,arial,sans-serif,helvetica;color: #521410; text-align: center;">Konto erfolgreich registriert: </div>';
$LANG['de']['footer1']='<div style="font-family: berliner,arial,sans-serif,helvetica;font-size: 12px;color: #521410; text-align: center;">
<p>Das elektronische W&ouml;rterbuch wurde von <a href="mailto:azirionq@yahoo.com.mx">Antonio Ziri&oacute;n Quijano</a>
im <a target=_top href="http://www.filosoficas.unam.mx">Instituto de Investigaciones Filos&oacute;ficas</a> der <a target=_top href="http://www.unam.mx">Universidad Nacional Aut&oacute;noma de M&eacute;xico.</a> konzipiert und&nbsp;&nbsp;erstellt.</div>';
$LANG['de']['footer2']='<div style="font-family: berliner,arial,sans-serif,helvetica;font-size: 11px;color: #521410; text-align: center;">(C) Antonio Ziri&oacute;n Quijano, 2006.  Alle Rechte vorbehalten.</div>';
##### Español
$LANG['es']['namelang']="Auf Deutsch: ";
$LANG['es']['search']="Suche auf Spanisch: ";
$LANG['es']['tosearch']="Suche!";
$LANG['es']['fullscreen']="";
$LANG['es']['goback']="Zur&uuml;ck";
$LANG['es']['word']="Palabra";
$LANG['es']['translation']="Traducci&oacute;n";
$LANG['es']['reference']="Hinweise";
$LANG['es']['also']="Sehen";
$LANG['es']['sonof']="hijo de";
$LANG['es']['addItem']="Agregar Palabra";
$LANG['es']['addUser']="Agregar Usuario";
$LANG['es']['changePass']="Cambiar Password";
$LANG['es']['add']="Agregar";
$LANG['es']['edit']="Editar";
$LANG['es']['del']="Borrar";
$LANG['es']['save']="Guardar";
$LANG['es']['modification']="Modificación Exitosa";
$LANG['es']['error']="Un error sucedi&oacute; al realizar la última operaci&oacute;n";
$LANG['es']['view']="Sehen";
$LANG['es']['de']="Deutsch";
$LANG['es']['es']="Spanisch";
$LANG['es']['level']="Stufe";
$LANG['es']['derived']="Ableitungsausdr&#252;cke:";
$LANG['es']['derivedfrom']="Abgeleitet von";
$LANG['es']['cursives']="Cursivas";
$LANG['es']['link']="link";
$LANG['es']['nosearch']="Es gibt kein Register mehr<br>oder Sie haben keine Suche gestartet";
$LANG['es']['previous']="Die 25 vorhergehende";
$LANG['es']['next']="Die 25 folgende";
$LANG['es']['download']="Herunterladen";

//$LANG['es']['']="";
//$LANG['es']['']="";
?>
